language: python
python:
  - "3.6"      # current default Python on Travis CI

# command to install dependencies
install:
  - pip install flake8 -r requirements.txt
  - pip install libra

script:
  - flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
  - python -m unittest discover ./tests "tests.py"
